#!/bin/bash

pushd ~/projects/carhud/yocto-out

echo "STARTING DOCKER: TACOS-YOCTO"
# NEED PRIVILEGED FLAG FOR LOOPBACK DEVICE
docker run -it --interactive --privileged --workdir /home/build --volume ${PWD}:/home/build/shared tacos-yocto
